#include <cstdlib>

/**
 * This is a template for `clang-format` configuration files. A valid
 * configuration is a subset of this structure where arrays indicate
 * alternatives that can be selected, and the `null` value indicates
 * a field can be omitted entirely.
 *
 * The `evolve` protocol supports a `evolve.template` request that
 * expects such a template as response and allows an independent tool
 * to respond to requests like `evolve.generate`, `evolve.variate`,
 * and `evolve.combine`.
 */
static const char* const g_template = R"({
  "AccessModifierOffset": [ null, -4, -3, -2, -1, 0, 1, 2, 3, 4 ],
  "AlignAfterOpenBracket": [ null, "Align", "DontAlign", "AlwaysBreak" ],
  "AlignConsecutiveAssignments": [ null, true, false ],
  "AlignConsecutiveDeclarations": [ null, true, false ],
  "AlignEscapedNewlines": [ null, "Right", "Left", "DontAlign" ],
  "AlignOperands": [ null, true, false ],
  "AlignTrailingComments": [ null, true, false ],
  "AllowAllParametersOfDeclarationOnNextLine": [ null, true, false ],
  "AllowShortBlocksOnASingleLine": [ null, true, false ],
  "AllowShortCaseLabelsOnASingleLine": [ null, true, false ],
  "AllowShortFunctionsOnASingleLine": [ null, "All", "Inline", "Empty", "InlineOnly", "None" ],
  "AllowShortIfStatementsOnASingleLine": [ null, true, false ],
  "AllowShortLoopsOnASingleLine": [ null, true, false ],
  "AlwaysBreakAfterDefinitionReturnType": [ null, "None", "All", "TopLevel" ],
  "AlwaysBreakAfterReturnType": [ null, "None", "All", "TopLevel", "AllDefinitions", "TopLevelDefinitions" ],
  "AlwaysBreakBeforeMultilineStrings": [ null, true, false ],
  "AlwaysBreakTemplateDeclarations": [ null, true, false ],
  "BinPackArguments": [ null, true, false ],
  "BinPackParameters": [ null, true, false ],
  "BraceWrapping": {
    "AfterClass": [ null, true, false ],
    "AfterControlStatement": [ null, true, false ],
    "AfterEnum": [ null, true, false ],
    "AfterFunction": [ null, true, false ],
    "AfterNamespace": [ null, true, false ],
    "AfterObjCDeclaration": [ null, true, false ],
    "AfterStruct": [ null, true, false ],
    "AfterUnion": [ null, true, false ],
    "AfterExternBlock": [ null, true, false ],
    "BeforeCatch": [ null, true, false ],
    "BeforeElse": [ null, true, false ],
    "IndentBraces": [ null, true, false ],
    "SplitEmptyFunction": [ null, true, false ],
    "SplitEmptyRecord": [ null, true, false ],
    "SplitEmptyNamespace": [ null, true, false ]
  },
  "BreakBeforeBinaryOperators": [ null, "None", "NonAssignment", "All" ],
  "BreakBeforeBraces": [ null, "Attach", "Linux", "Mozilla", "Stroustrup", "Allman", "GNU", "WebKit", "Custom" ],
  "BreakBeforeInheritanceComma": [ null, true, false ],
  "BreakBeforeTernaryOperators": [ null, true, false ],
  "BreakConstructorInitializersBeforeComma": [ null, true, false ],
  "BreakConstructorInitializers": [ null, "BeforeColon", "BeforeComma", "AfterColon" ],
  "BreakAfterJavaFieldAnnotations": [ null, true, false ],
  "BreakStringLiterals": [ null, true, false ],
  "ColumnLimit": [ null, 70, 72, 74, 76, 78, 80, 84, 88, 89, 90, 98 ],
  "CompactNamespaces": [ null, true, false ],
  "ConstructorInitializerAllOnOneLineOrOnePerLine": [ null, true, false ],
  "ConstructorInitializerIndentWidth": [ null, 0, 1, 2, 3, 4, 5, 6, 7, 8 ],
  "ContinuationIndentWidth": [ null, 0, 1, 2, 3, 4, 5, 6, 7, 8 ],
  "Cpp11BracedListStyle": [ null, true, false ],
  "DerivePointerAlignment": [ null, true, false ],
  "ExperimentalAutoDetectBinPacking": [ null, true, false ],
  "FixNamespaceComments": [ null, true, false ],
  "IncludeBlocks": [ null, "Preserve", "Merge", "Regroup" ],
  "IndentCaseLabels": [ null, true, false ],
  "IndentPPDirectives": [ null, "None", "AfterHash" ],
  "IndentWidth": [ null, 0, 1, 2, 3, 4, 5, 6, 7, 8 ],
  "IndentWrappedFunctionNames": [ null, true, false ],
  "JavaScriptQuotes": [ null, "Single", "Double", "Leave" ],
  "JavaScriptWrapImports": [ null, true, false ],
  "KeepEmptyLinesAtTheStartOfBlocks": [ null, true, false ],
  "MaxEmptyLinesToKeep": [ null, 0, 1, 2, 3, 4 ],
  "NamespaceIndentation": [ null, "None", "Inner", "All" ],
  "ObjCBlockIndentWidth": [ null, 0, 1, 2, 3, 4 ],
  "ObjCSpaceAfterProperty": [ null, true, false ],
  "ObjCSpaceBeforeProtocolList": [ null, true, false ],
  "PointerAlignment": [ null, "Left", "Middle", "Right" ],
  "ReflowComments": [ null, true, false ],
  "SortIncludes": [ null, true, false ],
  "SortUsingDeclarations": [ null, true, false ],
  "SpaceAfterCStyleCast": [ null, true, false ],
  "SpaceAfterTemplateKeyword": [ null, true, false ],
  "SpaceBeforeAssignmentOperators": [ null, true, false ],
  "SpaceBeforeParens": [ null, "Never", "ControlStatements", "Always" ],
  "SpaceInEmptyParentheses": [ null, true, false ],
  "SpacesBeforeTrailingComments": [ null, 0, 1, 2, 3, 4, 5, 6, 7, 8 ],
  "SpacesInAngles": [ null, true, false ],
  "SpacesInContainerLiterals": [ null, true, false ],
  "SpacesInCStyleCastParentheses": [ null, true, false ],
  "SpacesInParentheses": [ null, true, false ],
  "SpacesInSquareBrackets": [ null, true, false ],
  "Standard": [ null, "Cpp11", "Cpp03", "Auto" ],
  "TabWidth": [ null, 2, 4, 8 ],
  "UseTab": [ null, "ForIndentation", "ForContinuationAndIndentation", "Always", "Never" ]
})";

/**
 * `clang-format` comes with various presets that can be inherited
 * from in configuration files with `BasedOnStyle: GNU`. The command
 * line utility can also dump the full configuration with something
 * like `clang-format -style='{"BasedOnStyle":"GNU"}' -dump-config`.
 * Remove options that are not part of our template (see above) and
 * you get the presets here.
 *
 * It would be nice to generate these dynamically, `clang::format`
 * however only generates YAML while we can only handle JSON without
 * adding another library. And LLVM has support for both, but there
 * does not seem to be an easy way to use those implementations to
 * convert YAML to JSON, so they are hardcoded here.
 */
static const char* const g_presets[] = {
  R"({
    "AccessModifierOffset": -1,
    "AlignAfterOpenBracket": "Align",
    "AlignConsecutiveAssignments": false,
    "AlignConsecutiveDeclarations": false,
    "AlignEscapedNewlines": "Left",
    "AlignOperands": true,
    "AlignTrailingComments": true,
    "AllowAllParametersOfDeclarationOnNextLine": false,
    "AllowShortBlocksOnASingleLine": false,
    "AllowShortCaseLabelsOnASingleLine": false,
    "AllowShortFunctionsOnASingleLine": "Inline",
    "AllowShortIfStatementsOnASingleLine": false,
    "AllowShortLoopsOnASingleLine": false,
    "AlwaysBreakAfterDefinitionReturnType": "None",
    "AlwaysBreakAfterReturnType": "None",
    "AlwaysBreakBeforeMultilineStrings": true,
    "AlwaysBreakTemplateDeclarations": true,
    "BinPackArguments": true,
    "BinPackParameters": false,
    "BraceWrapping": {
      "AfterClass": false,
      "AfterControlStatement": false,
      "AfterEnum": false,
      "AfterExternBlock": false,
      "AfterFunction": false,
      "AfterNamespace": false,
      "AfterObjCDeclaration": false,
      "AfterStruct": false,
      "AfterUnion": false,
      "BeforeCatch": false,
      "BeforeElse": false,
      "IndentBraces": false,
      "SplitEmptyFunction": true,
      "SplitEmptyNamespace": true,
      "SplitEmptyRecord": true
    },
    "BreakAfterJavaFieldAnnotations": false,
    "BreakBeforeBinaryOperators": "None",
    "BreakBeforeBraces": "Attach",
    "BreakBeforeInheritanceComma": false,
    "BreakBeforeTernaryOperators": true,
    "BreakConstructorInitializers": "BeforeColon",
    "BreakConstructorInitializersBeforeComma": false,
    "BreakStringLiterals": true,
    "ColumnLimit": 80,
    "CompactNamespaces": false,
    "ConstructorInitializerAllOnOneLineOrOnePerLine": true,
    "ConstructorInitializerIndentWidth": 4,
    "ContinuationIndentWidth": 4,
    "Cpp11BracedListStyle": true,
    "DerivePointerAlignment": false,
    "ExperimentalAutoDetectBinPacking": false,
    "FixNamespaceComments": true,
    "IncludeBlocks": "Preserve",
    "IndentCaseLabels": true,
    "IndentPPDirectives": "None",
    "IndentWidth": 2,
    "IndentWrappedFunctionNames": false,
    "JavaScriptQuotes": "Leave",
    "JavaScriptWrapImports": true,
    "KeepEmptyLinesAtTheStartOfBlocks": false,
    "MaxEmptyLinesToKeep": 1,
    "NamespaceIndentation": "None",
    "ObjCBlockIndentWidth": 2,
    "ObjCSpaceAfterProperty": false,
    "ObjCSpaceBeforeProtocolList": false,
    "PointerAlignment": "Left",
    "ReflowComments": true,
    "SortIncludes": true,
    "SortUsingDeclarations": true,
    "SpaceAfterCStyleCast": false,
    "SpaceAfterTemplateKeyword": true,
    "SpaceBeforeAssignmentOperators": true,
    "SpaceBeforeParens": "ControlStatements",
    "SpaceInEmptyParentheses": false,
    "SpacesBeforeTrailingComments": 2,
    "SpacesInAngles": false,
    "SpacesInCStyleCastParentheses": false,
    "SpacesInContainerLiterals": true,
    "SpacesInParentheses": false,
    "SpacesInSquareBrackets": false,
    "Standard": "Auto",
    "TabWidth": 8,
    "UseTab": "Never"
  })",
  R"({
    "AccessModifierOffset": -1,
    "AlignAfterOpenBracket": "Align",
    "AlignConsecutiveAssignments": false,
    "AlignConsecutiveDeclarations": false,
    "AlignEscapedNewlines": "Left",
    "AlignOperands": true,
    "AlignTrailingComments": true,
    "AllowAllParametersOfDeclarationOnNextLine": true,
    "AllowShortBlocksOnASingleLine": false,
    "AllowShortCaseLabelsOnASingleLine": false,
    "AllowShortFunctionsOnASingleLine": "All",
    "AllowShortIfStatementsOnASingleLine": true,
    "AllowShortLoopsOnASingleLine": true,
    "AlwaysBreakAfterDefinitionReturnType": "None",
    "AlwaysBreakAfterReturnType": "None",
    "AlwaysBreakBeforeMultilineStrings": true,
    "AlwaysBreakTemplateDeclarations": true,
    "BinPackArguments": true,
    "BinPackParameters": true,
    "BraceWrapping": {
      "AfterClass": false,
      "AfterControlStatement": false,
      "AfterEnum": false,
      "AfterExternBlock": false,
      "AfterFunction": false,
      "AfterNamespace": false,
      "AfterObjCDeclaration": false,
      "AfterStruct": false,
      "AfterUnion": false,
      "BeforeCatch": false,
      "BeforeElse": false,
      "IndentBraces": false,
      "SplitEmptyFunction": true,
      "SplitEmptyNamespace": true,
      "SplitEmptyRecord": true
    },
    "BreakAfterJavaFieldAnnotations": false,
    "BreakBeforeBinaryOperators": "None",
    "BreakBeforeBraces": "Attach",
    "BreakBeforeInheritanceComma": false,
    "BreakBeforeTernaryOperators": true,
    "BreakConstructorInitializers": "BeforeColon",
    "BreakConstructorInitializersBeforeComma": false,
    "BreakStringLiterals": true,
    "ColumnLimit": 80,
    "CompactNamespaces": false,
    "ConstructorInitializerAllOnOneLineOrOnePerLine": true,
    "ConstructorInitializerIndentWidth": 4,
    "ContinuationIndentWidth": 4,
    "Cpp11BracedListStyle": true,
    "DerivePointerAlignment": true,
    "ExperimentalAutoDetectBinPacking": false,
    "FixNamespaceComments": true,
    "IncludeBlocks": "Preserve",
    "IndentCaseLabels": true,
    "IndentPPDirectives": "None",
    "IndentWidth": 2,
    "IndentWrappedFunctionNames": false,
    "JavaScriptQuotes": "Leave",
    "JavaScriptWrapImports": true,
    "KeepEmptyLinesAtTheStartOfBlocks": false,
    "MaxEmptyLinesToKeep": 1,
    "NamespaceIndentation": "None",
    "ObjCBlockIndentWidth": 2,
    "ObjCSpaceAfterProperty": false,
    "ObjCSpaceBeforeProtocolList": false,
    "PointerAlignment": "Left",
    "ReflowComments": true,
    "SortIncludes": true,
    "SortUsingDeclarations": true,
    "SpaceAfterCStyleCast": false,
    "SpaceAfterTemplateKeyword": true,
    "SpaceBeforeAssignmentOperators": true,
    "SpaceBeforeParens": "ControlStatements",
    "SpaceInEmptyParentheses": false,
    "SpacesBeforeTrailingComments": 2,
    "SpacesInAngles": false,
    "SpacesInCStyleCastParentheses": false,
    "SpacesInContainerLiterals": true,
    "SpacesInParentheses": false,
    "SpacesInSquareBrackets": false,
    "Standard": "Auto",
    "TabWidth": 8,
    "UseTab": "Never"
  })",
  R"({
    "AccessModifierOffset": -2,
    "AlignAfterOpenBracket": "Align",
    "AlignConsecutiveAssignments": false,
    "AlignConsecutiveDeclarations": false,
    "AlignEscapedNewlines": "Right",
    "AlignOperands": true,
    "AlignTrailingComments": true,
    "AllowAllParametersOfDeclarationOnNextLine": false,
    "AllowShortBlocksOnASingleLine": false,
    "AllowShortCaseLabelsOnASingleLine": false,
    "AllowShortFunctionsOnASingleLine": "Inline",
    "AllowShortIfStatementsOnASingleLine": false,
    "AllowShortLoopsOnASingleLine": false,
    "AlwaysBreakAfterDefinitionReturnType": "TopLevel",
    "AlwaysBreakAfterReturnType": "TopLevel",
    "AlwaysBreakBeforeMultilineStrings": false,
    "AlwaysBreakTemplateDeclarations": true,
    "BinPackArguments": false,
    "BinPackParameters": false,
    "BraceWrapping": {
      "AfterClass": true,
      "AfterControlStatement": false,
      "AfterEnum": true,
      "AfterExternBlock": true,
      "AfterFunction": true,
      "AfterNamespace": false,
      "AfterObjCDeclaration": false,
      "AfterStruct": true,
      "AfterUnion": true,
      "BeforeCatch": false,
      "BeforeElse": false,
      "IndentBraces": false,
      "SplitEmptyFunction": true,
      "SplitEmptyNamespace": true,
      "SplitEmptyRecord": false
    },
    "BreakAfterJavaFieldAnnotations": false,
    "BreakBeforeBinaryOperators": "None",
    "BreakBeforeBraces": "Mozilla",
    "BreakBeforeInheritanceComma": true,
    "BreakBeforeTernaryOperators": true,
    "BreakConstructorInitializers": "BeforeComma",
    "BreakConstructorInitializersBeforeComma": false,
    "BreakStringLiterals": true,
    "ColumnLimit": 80,
    "CompactNamespaces": false,
    "ConstructorInitializerAllOnOneLineOrOnePerLine": false,
    "ConstructorInitializerIndentWidth": 2,
    "ContinuationIndentWidth": 2,
    "Cpp11BracedListStyle": false,
    "DerivePointerAlignment": false,
    "ExperimentalAutoDetectBinPacking": false,
    "FixNamespaceComments": false,
    "IncludeBlocks": "Preserve",
    "IndentCaseLabels": true,
    "IndentPPDirectives": "None",
    "IndentWidth": 2,
    "IndentWrappedFunctionNames": false,
    "JavaScriptQuotes": "Leave",
    "JavaScriptWrapImports": true,
    "KeepEmptyLinesAtTheStartOfBlocks": true,
    "MaxEmptyLinesToKeep": 1,
    "NamespaceIndentation": "None",
    "ObjCBlockIndentWidth": 2,
    "ObjCSpaceAfterProperty": true,
    "ObjCSpaceBeforeProtocolList": false,
    "PointerAlignment": "Left",
    "ReflowComments": true,
    "SortIncludes": true,
    "SortUsingDeclarations": true,
    "SpaceAfterCStyleCast": false,
    "SpaceAfterTemplateKeyword": false,
    "SpaceBeforeAssignmentOperators": true,
    "SpaceBeforeParens": "ControlStatements",
    "SpaceInEmptyParentheses": false,
    "SpacesBeforeTrailingComments": 1,
    "SpacesInAngles": false,
    "SpacesInCStyleCastParentheses": false,
    "SpacesInContainerLiterals": true,
    "SpacesInParentheses": false,
    "SpacesInSquareBrackets": false,
    "Standard": "Cpp11",
    "TabWidth": 8,
    "UseTab": "Never"
  })",
  R"({
    "AccessModifierOffset": -2,
    "AlignAfterOpenBracket": "Align",
    "AlignConsecutiveAssignments": false,
    "AlignConsecutiveDeclarations": false,
    "AlignEscapedNewlines": "Right",
    "AlignOperands": true,
    "AlignTrailingComments": true,
    "AllowAllParametersOfDeclarationOnNextLine": true,
    "AllowShortBlocksOnASingleLine": false,
    "AllowShortCaseLabelsOnASingleLine": false,
    "AllowShortFunctionsOnASingleLine": "All",
    "AllowShortIfStatementsOnASingleLine": false,
    "AllowShortLoopsOnASingleLine": false,
    "AlwaysBreakAfterDefinitionReturnType": "All",
    "AlwaysBreakAfterReturnType": "AllDefinitions",
    "AlwaysBreakBeforeMultilineStrings": false,
    "AlwaysBreakTemplateDeclarations": false,
    "BinPackArguments": true,
    "BinPackParameters": true,
    "BraceWrapping": {
      "AfterClass": true,
      "AfterControlStatement": true,
      "AfterEnum": true,
      "AfterExternBlock": true,
      "AfterFunction": true,
      "AfterNamespace": true,
      "AfterObjCDeclaration": true,
      "AfterStruct": true,
      "AfterUnion": true,
      "BeforeCatch": true,
      "BeforeElse": true,
      "IndentBraces": true,
      "SplitEmptyFunction": true,
      "SplitEmptyNamespace": true,
      "SplitEmptyRecord": true
    },
    "BreakAfterJavaFieldAnnotations": false,
    "BreakBeforeBinaryOperators": "All",
    "BreakBeforeBraces": "GNU",
    "BreakBeforeInheritanceComma": false,
    "BreakBeforeTernaryOperators": true,
    "BreakConstructorInitializers": "BeforeColon",
    "BreakConstructorInitializersBeforeComma": false,
    "BreakStringLiterals": true,
    "ColumnLimit": 79,
    "CompactNamespaces": false,
    "ConstructorInitializerAllOnOneLineOrOnePerLine": false,
    "ConstructorInitializerIndentWidth": 4,
    "ContinuationIndentWidth": 4,
    "Cpp11BracedListStyle": false,
    "DerivePointerAlignment": false,
    "ExperimentalAutoDetectBinPacking": false,
    "FixNamespaceComments": false,
    "IncludeBlocks": "Preserve",
    "IndentCaseLabels": false,
    "IndentPPDirectives": "None",
    "IndentWidth": 2,
    "IndentWrappedFunctionNames": false,
    "JavaScriptQuotes": "Leave",
    "JavaScriptWrapImports": true,
    "KeepEmptyLinesAtTheStartOfBlocks": true,
    "MaxEmptyLinesToKeep": 1,
    "NamespaceIndentation": "None",
    "ObjCBlockIndentWidth": 2,
    "ObjCSpaceAfterProperty": false,
    "ObjCSpaceBeforeProtocolList": true,
    "PointerAlignment": "Right",
    "ReflowComments": true,
    "SortIncludes": true,
    "SortUsingDeclarations": true,
    "SpaceAfterCStyleCast": false,
    "SpaceAfterTemplateKeyword": true,
    "SpaceBeforeAssignmentOperators": true,
    "SpaceBeforeParens": "Always",
    "SpaceInEmptyParentheses": false,
    "SpacesBeforeTrailingComments": 1,
    "SpacesInAngles": false,
    "SpacesInCStyleCastParentheses": false,
    "SpacesInContainerLiterals": true,
    "SpacesInParentheses": false,
    "SpacesInSquareBrackets": false,
    "Standard": "Cpp03",
    "TabWidth": 8,
    "UseTab": "Never"
  })",
  R"({
    "AccessModifierOffset": -2,
    "AlignAfterOpenBracket": "Align",
    "AlignConsecutiveAssignments": false,
    "AlignConsecutiveDeclarations": false,
    "AlignEscapedNewlines": "Right",
    "AlignOperands": true,
    "AlignTrailingComments": true,
    "AllowAllParametersOfDeclarationOnNextLine": true,
    "AllowShortBlocksOnASingleLine": false,
    "AllowShortCaseLabelsOnASingleLine": false,
    "AllowShortFunctionsOnASingleLine": "All",
    "AllowShortIfStatementsOnASingleLine": false,
    "AllowShortLoopsOnASingleLine": false,
    "AlwaysBreakAfterDefinitionReturnType": "None",
    "AlwaysBreakAfterReturnType": "None",
    "AlwaysBreakBeforeMultilineStrings": false,
    "AlwaysBreakTemplateDeclarations": false,
    "BinPackArguments": true,
    "BinPackParameters": true,
    "BraceWrapping": {
      "AfterClass": false,
      "AfterControlStatement": false,
      "AfterEnum": false,
      "AfterExternBlock": false,
      "AfterFunction": false,
      "AfterNamespace": false,
      "AfterObjCDeclaration": false,
      "AfterStruct": false,
      "AfterUnion": false,
      "BeforeCatch": false,
      "BeforeElse": false,
      "IndentBraces": false,
      "SplitEmptyFunction": true,
      "SplitEmptyNamespace": true,
      "SplitEmptyRecord": true
    },
    "BreakAfterJavaFieldAnnotations": false,
    "BreakBeforeBinaryOperators": "None",
    "BreakBeforeBraces": "Attach",
    "BreakBeforeInheritanceComma": false,
    "BreakBeforeTernaryOperators": true,
    "BreakConstructorInitializers": "BeforeColon",
    "BreakConstructorInitializersBeforeComma": false,
    "BreakStringLiterals": true,
    "ColumnLimit": 80,
    "CompactNamespaces": false,
    "ConstructorInitializerAllOnOneLineOrOnePerLine": false,
    "ConstructorInitializerIndentWidth": 4,
    "ContinuationIndentWidth": 4,
    "Cpp11BracedListStyle": true,
    "DerivePointerAlignment": false,
    "ExperimentalAutoDetectBinPacking": false,
    "FixNamespaceComments": true,
    "IncludeBlocks": "Preserve",
    "IndentCaseLabels": false,
    "IndentPPDirectives": "None",
    "IndentWidth": 2,
    "IndentWrappedFunctionNames": false,
    "JavaScriptQuotes": "Leave",
    "JavaScriptWrapImports": true,
    "KeepEmptyLinesAtTheStartOfBlocks": true,
    "MaxEmptyLinesToKeep": 1,
    "NamespaceIndentation": "None",
    "ObjCBlockIndentWidth": 2,
    "ObjCSpaceAfterProperty": false,
    "ObjCSpaceBeforeProtocolList": true,
    "PointerAlignment": "Right",
    "ReflowComments": true,
    "SortIncludes": true,
    "SortUsingDeclarations": true,
    "SpaceAfterCStyleCast": false,
    "SpaceAfterTemplateKeyword": true,
    "SpaceBeforeAssignmentOperators": true,
    "SpaceBeforeParens": "ControlStatements",
    "SpaceInEmptyParentheses": false,
    "SpacesBeforeTrailingComments": 1,
    "SpacesInAngles": false,
    "SpacesInCStyleCastParentheses": false,
    "SpacesInContainerLiterals": true,
    "SpacesInParentheses": false,
    "SpacesInSquareBrackets": false,
    "Standard": "Cpp11",
    "TabWidth": 8,
    "UseTab": "Never"
  })",
  R"({
    "AccessModifierOffset": -4,
    "AlignAfterOpenBracket": "DontAlign",
    "AlignConsecutiveAssignments": false,
    "AlignConsecutiveDeclarations": false,
    "AlignEscapedNewlines": "Right",
    "AlignOperands": false,
    "AlignTrailingComments": false,
    "AllowAllParametersOfDeclarationOnNextLine": true,
    "AllowShortBlocksOnASingleLine": false,
    "AllowShortCaseLabelsOnASingleLine": false,
    "AllowShortFunctionsOnASingleLine": "All",
    "AllowShortIfStatementsOnASingleLine": false,
    "AllowShortLoopsOnASingleLine": false,
    "AlwaysBreakAfterDefinitionReturnType": "None",
    "AlwaysBreakAfterReturnType": "None",
    "AlwaysBreakBeforeMultilineStrings": false,
    "AlwaysBreakTemplateDeclarations": false,
    "BinPackArguments": true,
    "BinPackParameters": true,
    "BraceWrapping": {
      "AfterClass": false,
      "AfterControlStatement": false,
      "AfterEnum": false,
      "AfterExternBlock": false,
      "AfterFunction": true,
      "AfterNamespace": false,
      "AfterObjCDeclaration": false,
      "AfterStruct": false,
      "AfterUnion": false,
      "BeforeCatch": false,
      "BeforeElse": false,
      "IndentBraces": false,
      "SplitEmptyFunction": true,
      "SplitEmptyNamespace": true,
      "SplitEmptyRecord": true
    },
    "BreakAfterJavaFieldAnnotations": false,
    "BreakBeforeBinaryOperators": "All",
    "BreakBeforeBraces": "WebKit",
    "BreakBeforeInheritanceComma": false,
    "BreakBeforeTernaryOperators": true,
    "BreakConstructorInitializers": "BeforeComma",
    "BreakConstructorInitializersBeforeComma": false,
    "BreakStringLiterals": true,
    "ColumnLimit": 0,
    "CompactNamespaces": false,
    "ConstructorInitializerAllOnOneLineOrOnePerLine": false,
    "ConstructorInitializerIndentWidth": 4,
    "ContinuationIndentWidth": 4,
    "Cpp11BracedListStyle": false,
    "DerivePointerAlignment": false,
    "ExperimentalAutoDetectBinPacking": false,
    "FixNamespaceComments": false,
    "IncludeBlocks": "Preserve",
    "IndentCaseLabels": false,
    "IndentPPDirectives": "None",
    "IndentWidth": 4,
    "IndentWrappedFunctionNames": false,
    "JavaScriptQuotes": "Leave",
    "JavaScriptWrapImports": true,
    "KeepEmptyLinesAtTheStartOfBlocks": true,
    "MaxEmptyLinesToKeep": 1,
    "NamespaceIndentation": "Inner",
    "ObjCBlockIndentWidth": 4,
    "ObjCSpaceAfterProperty": true,
    "ObjCSpaceBeforeProtocolList": true,
    "PointerAlignment": "Left",
    "ReflowComments": true,
    "SortIncludes": true,
    "SortUsingDeclarations": true,
    "SpaceAfterCStyleCast": false,
    "SpaceAfterTemplateKeyword": true,
    "SpaceBeforeAssignmentOperators": true,
    "SpaceBeforeParens": "ControlStatements",
    "SpaceInEmptyParentheses": false,
    "SpacesBeforeTrailingComments": 1,
    "SpacesInAngles": false,
    "SpacesInCStyleCastParentheses": false,
    "SpacesInContainerLiterals": true,
    "SpacesInParentheses": false,
    "SpacesInSquareBrackets": false,
    "Standard": "Cpp11",
    "TabWidth": 8,
    "UseTab": "Never"
  })",
  NULL};
